version: '3'
services:

  blender:
    image: nytimes/blender:2.92-cpu-ubuntu18.04

  caddy:
    image: caddy:2.1.1
    restart: always
    ports:
      - '80:80'
      - '443:443'
    environment:
      XDG_DATA_HOME: /mount/server/data
      XDG_CONFIG_HOME: /mount/server/config
    volumes:
      - ~/dental-model-maker/dev/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ~/mnt/caddy_server:/mount/server
      - ~/dental-model-maker/dev/root:/www/root

  postgres:
    image: "postgis/postgis:13-3.0-alpine" 
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_LOGIN}"
      POSTGRES_DB: Wecity
    ports:
      - '5432:5432'
    volumes:
      - ~/mnt/pg_data:/var/lib/postgresql/data
      - ~/dental-model-maker/dev/postgres:/scripts

  hasura:
    image: hasura/graphql-engine:v2.0.0-alpha.11
    ports:
    - "8080"
    depends_on:
      - postgres
      - hasura-backend-plus
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "host=postgres dbname=Wecity port=5432 user=${DB_LOGIN} password=${DB_PASSWORD}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: "$DB_PASSWORD"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "key": "$JWT_SECRET"}'
      HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: 'true'

  hasura-backend-plus:
    image: nhost/hasura-backend-plus:latest
    ports:
      - '3000'
    restart: always
    volumes:
      - ~/dental-model-maker/dev/hbp/custom:/custom
    environment:
      SERVER_URL: https://api.weee.city
      JWT_KEY: '$JWT_PRIVATE_KEY'
      JWT_KEY_FILE_PATH: custom/keys/private.pem
      HASURA_ENDPOINT: http://hasura:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: "$DB_PASSWORD"
      JWT_ALGORITHM: RS256
      S3_ENDPOINT: https://s3.eu-north-1.amazonaws.com
      S3_BUCKET: s3.weee.city
      S3_ACCESS_KEY_ID: AKIA2IYHTX7JSN5BFAEC
      S3_SECRET_ACCESS_KEY: '${S3_SECRET_ACCESS_KEY}'
      PROVIDER_SUCCESS_REDIRECT: 'https://weee.city/oauth/success'
      PROVIDER_FAILURE_REDIRECT: 'https://weee.city/oauth/failure'
      GOOGLE_ENABLE: 'true'
      GOOGLE_CLIENT_ID: '766690753861-u0muglqq0o81pu11cg1mnm3uh4grgprp.apps.googleusercontent.com'
      GOOGLE_CLIENT_SECRET: '${GOOGLE_CLIENT_SECRET}'
      FACEBOOK_ENABLE: 'true'
      FACEBOOK_CLIENT_ID: '1075569679634321'
      FACEBOOK_CLIENT_SECRET: '${FACEBOOK_CLIENT_SECRET}'
      AUTO_MIGRATE: 'true'
      COOKIE_SAME_SITE: 'none'
      COOKIE_SECURE: 'true'
      VERIFY_EMAILS: 'true'
      EMAILS_ENABLE: 'true'
      SMTP_HOST: 'email-smtp.eu-west-1.amazonaws.com'
      SMTP_PASS: '${SMTP_PASS}'
      SMTP_USER: 'AKIA2IYHTX7JSRJLISNC'
      SMTP_PORT: '587'
      SMTP_SECURE: 'false'
      SMTP_SENDER: 'hi@weee.city'
      NOTIFY_EMAIL_CHANGE: 'true'
      AUTO_ACTIVATE_NEW_USERS: 'true'
      REDIRECT_URL_SUCCESS: 'https://weee.city/'
      REDIRECT_URL_ERROR: 'https://weee.city/login-error'
      MIN_PASSWORD_LENGTH: 6
      DEFAULT_ALLOWED_USER_ROLES: user,me
      ALLOWED_USER_ROLES: user,me

  hasura-backend-plus-local:
    image: nhost/hasura-backend-plus:latest
    ports:
      - '3000'
    restart: always
    depends_on:
      - hasura-backend-plus
    volumes:
      - ~/dental-model-maker/dev/hbp/custom:/custom
    environment:
      SERVER_URL: https://api-local.weee.city
      JWT_KEY: '$JWT_PRIVATE_KEY'
      JWT_KEY_FILE_PATH: custom/keys/private.pem
      HASURA_ENDPOINT: http://hasura:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: "$DB_PASSWORD"
      JWT_ALGORITHM: RS256
      S3_ENDPOINT: https://s3.eu-north-1.amazonaws.com
      S3_BUCKET: s3.weee.city
      S3_ACCESS_KEY_ID: AKIA2IYHTX7JSN5BFAEC
      S3_SECRET_ACCESS_KEY: '${S3_SECRET_ACCESS_KEY}'
      PROVIDER_SUCCESS_REDIRECT: 'http://localhost:3000/oauth/success'
      PROVIDER_FAILURE_REDIRECT: 'http://localhost:3000/oauth/failure'
      GOOGLE_ENABLE: 'true'
      GOOGLE_CLIENT_ID: '766690753861-u0muglqq0o81pu11cg1mnm3uh4grgprp.apps.googleusercontent.com'
      GOOGLE_CLIENT_SECRET: '${GOOGLE_CLIENT_SECRET}'
      FACEBOOK_ENABLE: 'true'
      FACEBOOK_CLIENT_ID: '1075569679634321'
      FACEBOOK_CLIENT_SECRET: '${FACEBOOK_CLIENT_SECRET}'
      AUTO_MIGRATE: 'true'
      COOKIE_SAME_SITE: 'none'
      COOKIE_SECURE: 'true'
      VERIFY_EMAILS: 'true'
      EMAILS_ENABLE: 'true'
      SMTP_HOST: 'email-smtp.eu-west-1.amazonaws.com'
      SMTP_PASS: '${SMTP_PASS}'
      SMTP_USER: 'AKIA2IYHTX7JSRJLISNC'
      SMTP_PORT: '587'
      SMTP_SECURE: 'false'
      SMTP_SENDER: 'hi@weee.city'
      NOTIFY_EMAIL_CHANGE: 'true'
      AUTO_ACTIVATE_NEW_USERS: 'true'
      REDIRECT_URL_SUCCESS: 'http://localhost:3000/'
      REDIRECT_URL_ERROR: 'http://localhost:3000/login-error'
      MIN_PASSWORD_LENGTH: 6
      DEFAULT_ALLOWED_USER_ROLES: user,me
      ALLOWED_USER_ROLES: user,me

  minio:
    image: minio/minio
    restart: always
    environment:
      S3_BUCKET: hasura-backend-plus
      MINIO_ACCESS_KEY: AKIA2IYHTX7JSN5BFAEC
      MINIO_SECRET_KEY: '${S3_SECRET_ACCESS_KEY}' 
    entrypoint: sh
    command: "-c 'mkdir -p /export/hasura-backend-plus && /usr/bin/minio server /export'"
    volumes:
      - 'minio_data:/data'

volumes:
  db_data:
  minio_data:
